[SQUASH] avicii: Regenerate & update firmware
This is only history for proprietary-files.txt, other files like
extract-files.py is not here

commit 58a1ccefc97500fbc7132bcc6e97df11e118f756
Author: Nick Reuter <nreuter85@gmail.com>
Date:   Tue Dec 10 20:32:13 2024 -0600

    avicii: Address missing libbinder symbols in libwfdnative

    _ZN7android6binder12atrace_beginEmPKc
    _ZN7android6binder10atrace_endEm

    Change-Id: I942d51721461dbbf9c8d0f2f32128529bb7480c3

commit 9b7572c703d365e8956a87012d3b3baddfa1a350
Author: LuK1337 <priv.luk@gmail.com>
Date:   Fri Nov 22 12:40:16 2024 +0100

    avicii: Reapply blob patches with PatchELF 0.18.0

    Change-Id: I0b303f698095ba0bee2ff40e41e0c964bd0a3f4e

commit 96b1f87de79ebac86993de11af0212a18da77215
Author: LuK1337 <priv.luk@gmail.com>
Date:   Tue Nov 12 15:04:33 2024 +0100

    avicii: Update WFD system stack from OOS 14.0.0.602(EX01)

    Change-Id: Idec435e0b1645016620e5cdd094ed3fb1ae8b832

commit 00a3a67c54780db13b4e052dad6cecdb082fe854
Author: Hridaya Prajapati <info.hridayaprajapati@gmail.com>
Date:   Sat Sep 14 19:03:59 2024 +0545

    avicii: Setup prebuilt a-HAL

    Drop BOARD_USES_ALSA_AUDIO as it will declare audio.primary.lito, which
    is shipped prebuilt.
    Declare TARGET_PROVIDES_AUDIO_EXTNS as we ship prebuilt liba2dpoffload.

    Change-Id: I9e52f6b2bc6e105597e4f1ee291674f7af43fba3

commit d22a930abe7c0ccfc86e32920d74130439a19a87
Author: LuK1337 <priv.luk@gmail.com>
Date:   Sat Apr 5 22:18:31 2025 +0200

    avicii: libwfdservice_shim_v1 -> libwfdservice_shim

    Change-Id: Idf65dd61a2de80dfcbf72a8b75b6ca59234df573

commit 017e43071656643348c38a51054cd24993b36dad
Author: LuK1337 <priv.luk@gmail.com>
Date:   Tue Apr 1 16:11:23 2025 +0200

    avicii: Add libwfdservice_shim_v1 for WFD

    e69a5be2449122f90220151f9d01ace15221facf in system/hardware/interfaces
    broke the ABI ;'(

    Change-Id: I60691f2bab3f52fd9ade36ed6fcf6a2ef13a18c9

commit f329f4222db144ef1a67ecffadb015d546ef790b
Author: Michael Bestas <mkbestas@gmail.com>
Date:   Thu May 15 14:10:14 2025 +0530

    avicii: Enable ELF checks for libwpa_client dependent libs

    Change-Id: I490df02b68da4b9a7088a239672a1dcace66d270

commit cd2298d47d73df1444fb50edb190c487a1f912e5
Author: dianlujitao <dianlujitao@lineageos.org>
Date:   Thu May 15 13:31:20 2025 +0530

    avicii: remove OMX

     * OMX HW video codecs are no longer used after enabling Codec2
     * OMX HW audio codecs won't work without QCOM A/V enhancements, which
       we don't have on Lineage.

commit e364f2851512318de423cc78676aef2e3d515c28
Author: dianlujitao <dianlujitao@lineageos.org>
Date:   Thu May 15 13:21:43 2025 +0530

    avicii: Kang c2 codec config from NX659J

    Change-Id: I506d0b1d91c03c3d2d3a9af8e59b86fdb1f65363

commit 2989dd58ed0a25a3eb83d9bc2e74ed2149430a8a
Author: Michael Bestas <mkbestas@lineageos.org>
Date:   Thu May 15 13:05:35 2025 +0530

    avicii: Kang QTI codec2 stack from OnePlus 8T (KB2005_14.0.0.603(EX01))

    Change-Id: Ie14c6fd49ee8602b36eeef75cb29e5b09222642d

commit 1762812faf88a8c17cb5bd76896a314441b0e7ec
Author: sreeshankark <sreeshankar0910@gmail.com>
Date:   Tue May 13 13:08:23 2025 +0000

    avicii: Import media codecs configuration from vendor

commit b7c1df5110ca70bdc6536435197841adcb342187
Author: LuK1337 <priv.luk@gmail.com>
Date:   Wed May 14 21:31:34 2025 +0530

    avicii: Drop MAKE_COPY_RULE & MODULE_SUFFIX from display libs

    Reference: I800561a45de41e8f7f6150c1b156c84b430cee24
               I5429ecee3985e305290e312921725460ef195b83
    Change-Id: Ic9666f9aebdc3ed69c93d72585af66d4b45504d4

commit bf7831c0e81e04982c8ad7d2e60c8cb71ed2c043
Author: Nick Reuter <nreuter85@gmail.com>
Date:   Wed May 14 21:26:58 2025 +0530

    avicii: Bump libwfdservice to android.media.audio.common.types-V4

    Change-Id: I81060d8c73430a9598c676e18dc04e31a2f31c0c

commit 6b9d7664b1e7203d8c142206a8de8dc54802e5ec
Author: LuK1337 <priv.luk@gmail.com>
Date:   Wed May 14 21:24:57 2025 +0530

    avicii: Enable elfchecks for arcsoft libs

    Reference: I23190f0b83c9e28aa2624a7575544b0eaf5c83c8
    Change-Id: I18b0b07bf3a435dd449106653e3ca458b4f07b69

commit f80c08136804e1ebe9a1853c45a0ae0af83fd7b8
Author: LuK1337 <priv.luk@gmail.com>
Date:   Tue Nov 19 12:38:18 2024 +0100

    avicii: Enable elfchecks for libgpu_tonemapper/libgrallocutils

    Reference: I11dec853d8cfaddb01ba96a2e76be38fe2d52073
    Change-Id: I58f44f8486efff8ba26fe36860d890412f09316d

commit 591eff6d277a78768d894dc3fd4ca63aa9151008
Author: PRANAY BHARGAV BHAVARAJU <quic_pbhavara@quicinc.com>
Date:   Wed May 14 21:15:06 2025 +0530

    avicii: avoid setting permission for /dev/hw_random

    Below patch from system/core is setting required access policy
    for /dev/hw_random. And CTS test is updated accordingly

    https://android-review.googlesource.com/c/platform/system/core/+/2229337
    https://android-review.googlesource.com/c/platform/cts/+/2232052

    Change-Id: I762dfa3b1e84dee6c49fc178b5b75cf1c134cfb7

commit f113c9e326f8a90d24f94c8fc30f8950bb892daa
Author: LuK1337 <priv.luk@gmail.com>
Date:   Thu Oct 24 21:46:02 2024 +0200

    avicii: Declare adsp_avs_config.acdb symlink during extraction

    Change-Id: I5a328db61cbd83fe292522b90f21b85e94986381

commit 52f80d01d42bf173c6a72a59bbf6cb955bda402d
Author: LuK1337 <priv.luk@gmail.com>
Date:   Wed May 14 19:02:04 2025 +0530

    avicii: Add extra blobs to make checkelf happy

    Change-Id: I34945e373b62714538813cc0fd12ee8ad4f04e1f

commit e4124cfbe4f3570bcadf75168ded2eb5c2ad12ea
Author: Sebastiano Barezzi <seba@sebaubuntu.dev>
Date:   Wed May 14 18:42:03 2025 +0530

    avicii: Drop libril-qcril-hook-oem.so

    Requires libril, we disabled that target, safe to assume only non-qcrild
    uses this

commit 1e6ebaf5152188f0b6b5bf1a587b1a88dee24676
Author: Bruno Martins <bgcngm@gmail.com>
Date:   Wed May 14 18:39:26 2025 +0530

    avicii: Remove software OMX blobs

    Default to C2 codecs from swcodec apex.

    Change-Id: I32f0b0abe680c1f350268115a3cc5488a2a57ec3

commit 622ff05af6b8b2f5d2f8c3d2a895924082b4ea2b
Author: LuK1337 <priv.luk@gmail.com>
Date:   Wed May 14 14:23:00 2025 +0530

    avicii: Setup ELF checks

commit f9ddfc8d5bf9d749d81d8e7962877eb6899dfe97
Author: LuK1337 <priv.luk@gmail.com>
Date:   Wed May 14 14:04:12 2025 +0530

    avicii: Fix DT_SONAME for some camera libs

commit 3603412f75f8dc9c78828e17ac9cd42ecdf61af6
Author: LuK1337 <priv.luk@gmail.com>
Date:   Sat Oct 12 17:42:02 2024 +0200

    avicii: Shim WFD with libgui_shim/libinput_shim

    Change-Id: I42bf06bc6b19942303031ef0147dafa6df127fe5

commit 0fcd35eac182680c93ddd3fe2e60716f49f38cce
Author: Michael Bestas <mkbestas@lineageos.org>
Date:   Tue May 13 16:07:48 2025 +0000

    avicii: Patch libwfdservice to resolve duplicate dependencies

    Fixes:
    error: module "libwfdservice" variant
    "android_arm_armv8-a_cortex-a76_static": depends on multiple
    versions of the same aidl_interface:
    android.media.audio.common.types-V2-cpp-source,
    android.media.audio.common.types-V3-cpp-source

    Change-Id: I8086a80fcc238d6b03d16640ee2c4e134129bbab

Signed-off-by: hmtheboy154 <buingoc67@gmail.com>